---
- name: copy over elasticsearch.keystore to local
  connection: local
  delegate_to: localhost
  run_once: true
  become: false
  s3:
    bucket: "{{ elasticsearch_key_bucket }}"
    object: "elasticsearch_keys/elasticsearch.keystore"
    dest: ".tmp/elasticsearch.keystore"
    mode: get
  changed_when: false
  register: s3_keystore
  until: s3_keystore is succeeded
  retries: 10
  delay: 30

- name: Copy key to remote
  copy:
    src: ".tmp/elasticsearch.keystore"
    dest: "/etc/elasticsearch/elasticsearch.keystore"
    owner: "root"
    group: "elasticsearch"
    mode: "06400"
  changed_when: false

- name: remove temp local keystore
  connection: local
  delegate_to: localhost
  run_once: true
  become: false
  file:
    path: ./tmp/elasticsearch.keystore
    state: absent
  changed_when: false
  failed_when: false
