---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Configure Elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
  notify: restart elasticsearch

- name: install aws cloud plugin
  elasticsearch_plugin:
    name: cloud-aws
  when: aws_install

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes

