---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: ensure mounted directory permissions
  file:
    path: "{{ mtn_volume_mount['mount_path']}}"
    state: directory
    owner: "{{ mtn_volume_mount['mount_permissions']['owner']}}"
    group: "{{ mtn_volume_mount['mount_permissions']['group']}}"
  when: mtn_volume_mount['mount_permissions'] is defined

- name: Configure Elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
  notify: restart elasticsearch

- name: list plugins
  shell: "{{ es_home }}/bin/elasticsearch-plugin list | grep -v 'Installed plugins in'"
  register: installed_plugins
  changed_when: false

- name: install elasticsearch plugins
  shell: "{{ es_home }}/bin/elasticsearch-plugin install {{ item.src }}"
  with_items: "{{ elasticsearch_plugins }}"
  when: item.name not in installed_plugins.stdout and elasticsearch_plugins is defined

- block:
  - block:
    - name: check if aws cloud plugin is installed
      shell: >
         {{ es_home }}/bin/plugin list cloud-aws | sed -n '1!p' | cut -d '-' -f2-
      register: installed_plugin

    - name: install aws cloud plugin
      command: "{{ es_home }}/bin/plugin install cloud-aws"
      when: installed_plugin.stdout.find("cloud-aws") == -1
    when: elasticsearch_version < 5
##########################################################
# cloud-aws plugin is updated to discovery-ec2 in elastic5
###########################################################
  - block:
    - name: check if discovery ec2 plugin is installed
      shell: >
         {{ es_home }}/bin/elasticsearch-plugin list discovery-ec2 | sed -n '1!p' | cut -d '-' -f2-
      register: installed_plugin

    - name: install aws cloud plugin
      command: "{{ es_home }}/bin/elasticsearch-plugin install discovery-ec2"
      when: installed_plugin.stdout.find("discovery-ec2") == -1
    when: elasticsearch_version > 5

  when: aws_install is defined and aws_install

#- name: set elasticsearch JAVA_OPTS
#  lineinfile:
#    dest: /etc/default/elasticsearch
#    regexp: "^ES_JAVA_OPTS="
#    line: "ES_JAVA_OPTS=\"{{ elasticsearch_java_opts }}\""
#    insertafter: "^#ES_JAVA_OPTS"
#  notify: restart elasticsearch
#  when: elasticsearch_java_opts is defined

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes
