---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: ensure mounted directory permissions
  file:
    path: "{{ mtn_volume_mount['mount_path']}}"
    state: directory
    owner: "{{ mtn_volume_mount['mount_permissions']['owner']}}"
    group: "{{ mtn_volume_mount['mount_permissions']['group']}}"
  when: mtn_volume_mount['mount_permissions'] is defined

- name: Configure Elasticsearch.yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
  notify: restart elasticsearch

- name: list plugins
  shell: "{{ es_home }}/bin/plugin list | grep -v 'Installed plugins in'"
  register: installed_plugins
  changed_when: false

- name: install elasticsearch plugins
  shell: "{{ es_home }}/bin/plugin install {{ item.src }}"
  with_items: "{{ elasticsearch_plugins }}"
  when: item.name not in installed_plugins.stdout

- name: check if aws cloud plugin is installed
  shell: >
     {{ es_home }}/bin/plugin list cloud-aws | sed -n '1!p' | cut -d '-' -f2-
  register: installed_plugin
  when: aws_install is defined and aws_install

- name: install aws cloud plugin
  command: "{{ es_home }}/bin/plugin install cloud-aws"
  when: aws_install is defined and aws_install and installed_plugin.stdout.find("cloud-aws") == -1

- name: set elasticsearch JAVA_OPTS
  lineinfile:
    dest: /etc/default/elasticsearch
    regexp: "^ES_JAVA_OPTS="
    line: "ES_JAVA_OPTS=\"{{ elasticsearch_java_opts }}\""
    insertafter: "^#ES_JAVA_OPTS"
  notify: restart elasticsearch

  when: elasticsearch_java_opts is defined

- name: Start Elasticsearch.
  service: name=elasticsearch state=started enabled=yes
