---
- name: Add Elasticsearch apt key.
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
    state: present
    update_cache: yes

- name: Install Elasticsearch.
  apt: pkg=elasticsearch={{ elasticsearch_version }} state=present
  notify: restart elasticsearch

- name: Set JVM heap size
  lineinfile:
    dest: /etc/elasticsearch/jvm.options
    regexp: "-{{ item }}"
    line: "-{{ item }}{{ elasticsearch_heap_size }}"
  when: elasticsearch_heap_size is defined
  with_items:
    - Xms
    - Xmx
  notify: restart elasticsearch
